### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cervantes-loves-ai** [dolongbien/HumanBehaviorBKU#8]
when try to train the network, got this error

https://colab.research.google.com/drive/1FX8J7UioZKxuDAUz2y662_FJQ-bhXRu2

![image](https://user-images.githubusercontent.com/1273214/64705001-78a5ae00-d4af-11e9-9e8d-3e06ba41d420.png)

**Comment by dolongbien** [comment]
Hi, line 35 says that you might have the wrong input directory format. Recheck your input folder structure. Your `mydrive/Train_RoadAccidents` must have 2 directories similar to this:

.../mydrive/Train_RoadAccidents/

- Abnormal
- Normal

Put corresponding video feature files into those folders and try again.

**Comment by cervantes-loves-ai** [comment]
thank you for your quick response.

it seems that path of Normal and Abnotmal is ok,please have a look on my colab

https://colab.research.google.com/drive/1FX8J7UioZKxuDAUz2y662_FJQ-bhXRu2

![image](https://user-images.githubusercontent.com/1273214/64770023-a7259680-d54c-11e9-8c76-4785741e232a.png)

**Comment by dolongbien** [comment]
The error is pretty obvious and it depends heavily on your directory as much as your files/hidden files. I think you should examine those file/directories again and print out the variable for debugging. Also, I'm not sure if the video counting code above has ignored the hidden files yet, so check it yourself.

**Comment by dolongbien** [comment]
Hi, the problem is that you have more than 2 folders in **Train_RoadAccidents** dir:

`AllClassPath='/content/gdrive/My Drive/Colab Notebooks/Train_RoadAccidents/'
output_dir='/content/gdrive/My Drive/Colab Notebooks/Train_RoadAccidents/Result/Weight/'
loss_dir = '/content/gdrive/My Drive/Colab Notebooks/Train_RoadAccidents/Result/Loss'`

This initialization will generate 3 folders inside **Train_RoadAccidents** dir, which is wrong. Create an independent directory for each of them (Result, Test_RoadAccidents folder) and make sure there are only 2 (Normal and Abnormal) folders in Train_RoadAccidents dir.

Hope this help.
